name: CD - Deploy to AWS EKS using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}            # e.g., us-east-1
      CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}     # your-eks-cluster
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}             # hello-world-service
      IMAGE_TAG: ${{ secrets.IMAGE_TAG || 'latest' }}   # Optional tag override
      JFROG_REGISTRY: ${{ secrets.JFROG_REGISTRY }}     # sidgs.jfrog.io/sidgs

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy using Helm
        run: |
          helm upgrade --install $IMAGE_NAME ./helm/hello-world \
            --set image.repository=$JFROG_REGISTRY/$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG